# Generated by Django 2.1 on 2018-10-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='colour',
            field=models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Silver', 'Silver'), ('Black', 'Black')], max_length=50, null=True),
        ),
    ]
